name: Deploy to Local Docker

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger local server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.LOCAL_HOST }}
          username: ${{ secrets.LOCAL_USER }}
          key: ${{ secrets.LOCAL_SSH_KEY }}
          script: |
            cd /home/user/mlops-crop-prediction-cicd-project
            git pull origin main
            docker-compose up --build -d
