name: Deploy to EC2 Docker

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            set -e

            echo "Starting deployment..."

            # Move to home directory
            cd /home/ubuntu

            # Clone repo if not exists
            if [ ! -d "mlops-crop-prediction-cicd-project" ]; then
              git clone https://github.com/lekkalahyma/mlops-crop-prediction-cicd-project.git
            fi

            cd mlops-crop-prediction-cicd-project

            # Ensure latest code
            git pull origin main

            echo "Stopping old containers..."
            docker compose down || true

            echo "Building and starting containers..."
            docker compose up --build -d

            echo "Deployment completed successfully!"
