name: Deploy ML App to ECS

on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Get code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. AWS login (use IAM role / OIDC)
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::463436898355:role/action_role
        aws-region: ap-south-1
    - name: Debug AWS identity
      run: aws sts get-caller-identity     

    # 3. Login to ECR
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    # 4. Build Docker image
    - name: Build image
      run: docker build -t ml-app .

    # 5. Tag image
    - name: Tag image
      run: |
        docker tag ml-app:latest <account-id>.dkr.ecr.ap-south-1.amazonaws.com/ml-app:latest

    # 6. Push to ECR
    - name: Push image
      run: |
        docker push <account-id>.dkr.ecr.ap-south-1.amazonaws.com/ml-app:latest

    # 7. Deploy to ECS
    - name: Deploy to ECS
      run: |
        aws ecs update-service \
          --cluster my-cluster \
          --service my-service \
          --force-new-deployment
