name: ML Crop Prediction CI/CD

on:
  workflow_dispatch:
    
jobs:
  # ✅ JOB 1 - Test Code
  test:
    runs-on: ubuntu-latest
    steps:


    - name: Test SSH Connection
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: echo "SSH Connection Successful!"
